### ISSUE TITLE
Trouble creating CustomVisionTrainingClient

### ISSUE THREAD

**Issue by nancibles** [MicrosoftDocs/mslearn-cv-classify-bird-species#1]
I'm trying to run the example in Jupyter notebook as provided with no changes except to input my endpoint and training key. I am met with this TypeError every time. I couldn't find any information anywhere else so I was wondering if there's something I'm missing here? 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-70b1d99f1841> in <module>
      2 ENDPOINT = ""
      3 training_key = ""
----> 4 trainer = CustomVisionTrainingClient(training_key, endpoint=ENDPOINT)

TypeError: __init__() got multiple values for argument 'endpoint'
```

(I do have a valid endpoint and training key but took it out to make this post.)

**Comment by ktoliver** [comment]
@shanamatthews @cassieview for visibility

**Comment by shanamatthews** [comment]
Thanks for reporting this @nancibles ! The library we were using changed and we needed to update our sample code. We've published an update that fixed that sample code (which will be live at 4pm Pacific today), so if you try it again it should work for you!
